import './icon.css'

export * from './add'
export * from './arquivo-add'
export * from './arrow-back'
export * from './arrow-forward'
export * from './bin'
export * from './blocos'
export * from './calendario'
export * from './camera'
export * from './camera-sem'
export * from './close'
export * from './dots-horizontal-triple'
export * from './eye'
export * from './eye-blocked'
export * from './imagem'
export * from './mao'
export * from './mensagem'
export * from './menu'
export * from './microfone'
export * from './microfone-sem'
export * from './pencil'
export * from './search'
export * from './spinner'
export * from './telefone'
